### ISSUE TITLE
Violation of current Planka license

### ISSUE THREAD

**Issue by nickbe** [RARgames/4gaBoards#181]
Your source code indicates that you have copied code from the later AGPL Version of Planka into your own repository which you release under the MIT license. Please read the current license requirements for AGPL in GitHub and change your license accordingly to avoid conflict. You cannot preserve MIT while copying source code of AGPL at the same time. Please be fair to your fellow Github coders.
Thank you

**Comment by RARgames** [comment]
Thanks for stopping by @nickbe!

Code in this repo shouldn't contain any code from post-license-change Planka, however, if you feel that some files are copied please let me know (I'll review them and take action).

As you know this project was separated from Planka before the license change from MIT to AGPL.
The main reason for it was a different project vision and each commit makes more distance between Planka and this project.

**Comment by nickbe** [comment]
Hi again, 

well mostly the client folder is exactly the same as in Planka and maybe it's just a coincidence, but below are examples of what directly indicates copying.

Same code even with our TODO comments:
https://github.com/RARgames/4gaBoards/commit/2f7a0fd1f9ed679a4fe54d36f0e49049e95a4435#diff-be5098932cf33e0f8dbc249417bae18aee62c5010017cdbb1c341075b43498a7R11
https://github.com/RARgames/4gaBoards/commit/2f7a0fd1f9ed679a4fe54d36f0e49049e95a4435#diff-82f8eb03ae144fc89a3ac719b8aa284fe2cdd380164ea5dec06bba4de422bf3fR11

Accidental use of an env variable that doesn't exist in 4gaBoards, but does exist in Planka and was added in a recent change:
https://github.com/RARgames/4gaBoards/commit/2f7a0fd1f9ed679a4fe54d36f0e49049e95a4435#diff-a02703152c55b2353c1391ef431ec1aa69458600df8281b4482cc63f5f845743R34

Therefore we would ask you to update your license accordingly.
Thanks

**Comment by RARgames** [comment]
Please note that there might be some similarities in the client dir because both project share the same base code (under the MIT license).

The feat-sso branch was created by a new contributor and it's not the part of any release yet. There were no code reviews on our side as we've just received the information that it's ready for the initial testing. I'm sure that after testing it wouldn't be accepted.

We've decided to remove the branch until the case is resolved and we talk with the contributor.

If you have any other files/commits please let me know.

**Comment by nickbe** [comment]
Thanks for reviewing and taking action.
