### ISSUE TITLE
Website behind reverse proxy

### ISSUE THREAD

**Issue by simon-mueller** [RARgames/4gaBoards#266]
Hello,
I want to use the board behind a reverse proxy.

However, only a blank page is being shown. The logs don't reveal anything either.

Any hints?

I'm using Nginx Proxy Manager as reverse proxy.
https://fqdn.domain.tld ==> dockerhost:3000
SSL is enabled

**Comment by RARgames** [comment]
Hey,

this is most likely due to not setting `BASE_URL` variable in the `docker-compose.yml`, in your case, it should be:
`BASE_URL: https://fqdn.domain.tld`

Can you show a screenshot of this page with a browser console open?

Have you seen this [docs](https://github.com/RARgames/4gaBoards/blob/main/docs/ADDITIONAL_INFO.md#web-server-configuration-nginxapache) - the Nginx section?

Let me know if that helps!

**Comment by simon-mueller** [comment]
Thanks, working fine now!
