### ISSUE TITLE
The translation exists but is not displayed in the interface

### ISSUE THREAD

**Issue by zarevskaya** [RARgames/4gaBoards#376]
Hello,

Of the three translations, one is always displayed in English:

![Screenshot_20241020_001828](https://github.com/user-attachments/assets/efd36773-d6da-4c03-8bc7-7ac0fd9b40ce)

**Comment by zarevskaya** [comment]
The same here:

![Screenshot_20241020_055631](https://github.com/user-attachments/assets/8902f616-af44-44f6-8c00-8c9e5da9f320)

À tester | To Test

**Comment by RARgames** [comment]
1. Should be fixed in the next release: 3.0.6
2. List names are treated as user-generated content after creation - that's why it's not translated. However if you create new board (while using French language) all list names should be in French. 

We don't want to translate it, because it may cause confusion (+ users can edit these names), and users on one board are usually speaking the same language.

**Comment by zarevskaya** [comment]
Yes, that makes sense! ;)
Thanks for everything. The update is available, I will test it.

**Comment by RARgames** [comment]
The 3.0.6 should be in ~5m and it fixes the issue: "Subscribe to my own cards".

**Comment by zarevskaya** [comment]
Excellent! All work fine!

Take a look here: https://belginux.com/installer-4ga-boards-avec-docker/

**Comment by RARgames** [comment]
Looks great! Thanks.

If it's helpful for your article, you can add a link to this [docs website](https://docs.4gaboards.com/en/home) - as we don't have a full website yet (We should have it ready in ~2 weeks).

**Comment by zarevskaya** [comment]
No problem, it's done!

Thank you for the responsiveness and discussions. :)
